"""add created_by_id to products

Revision ID: f1ab5494b598
Revises: 2000df32aabd
Create Date: 2025-06-26 16:43:47.802770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ab5494b598'
down_revision = '2000df32aabd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'created_by_id')
    # ### end Alembic commands ###